// Copyright © 2026 幻心梦梦 (huanxinmengmeng)
// Licensed under the Apache License, Version 2.0 (the "License");
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use std::path::PathBuf;
use super::traits::{CodeGenerator, CodeGenOptions};
use super::target::TargetTriple;
use super::error::{CodeGenError, LinkError};
use crate::core::mlir;
use crate::core::mlir::ops::{HanshuOp, FanhuiOp, JiaOp, JianOp, ChengOp, ChuOp, IntLitOp, IdentOp};

/// GPU目标平台
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum GpuTarget {
    Cuda,
    Hip,
    OpenCL,
    Vulkan,
}

/// GPU后端实现
pub struct GpuBackend {
    target: GpuTarget,
    #[allow(dead_code)]
    options: CodeGenOptions,
}

impl GpuBackend {
    pub fn from_triple(triple: &TargetTriple) -> GpuTarget {
        if triple.as_str().contains("cuda") {
            GpuTarget::Cuda
        } else if triple.as_str().contains("hip") {
            GpuTarget::Hip
        } else if triple.as_str().contains("vulkan") {
            GpuTarget::Vulkan
        } else {
            GpuTarget::OpenCL
        }
    }
    
    /// 生成CUDA代码
    fn generate_cuda(&self, module: &mlir::ModuleOp) -> String {
        let mut code = String::new();
        code.push_str("// CUDA code generated by HuanLang\n");
        code.push_str("#include <cuda.h>\n");
        code.push_str("#include <cuda_runtime.h>\n\n");
        
        for op in &module.ops {
            if let Some(func) = op.as_any().downcast_ref::<HanshuOp>() {
                code.push_str(&format!("__global__ void {}() {{\n", func.name));
                for body_op in &func.body {
                    code.push_str(&self.generate_cuda_body(body_op));
                }
                code.push_str("}\n\n");
            }
        }
        
        code
    }
    
    /// 生成CUDA代码体
    fn generate_cuda_body(&self, op: &Box<dyn mlir::ops::HuanOp>) -> String {
        let mut code = String::new();
        
        if let Some(add) = op.as_any().downcast_ref::<JiaOp>() {
            code.push_str(&format!("  {} + {};", 
                self.generate_cuda_expr(&add.lhs), 
                self.generate_cuda_expr(&add.rhs)));
        } else if let Some(sub) = op.as_any().downcast_ref::<JianOp>() {
            code.push_str(&format!("  {} - {};", 
                self.generate_cuda_expr(&sub.lhs), 
                self.generate_cuda_expr(&sub.rhs)));
        } else if let Some(mul) = op.as_any().downcast_ref::<ChengOp>() {
            code.push_str(&format!("  {} * {};", 
                self.generate_cuda_expr(&mul.lhs), 
                self.generate_cuda_expr(&mul.rhs)));
        } else if let Some(div) = op.as_any().downcast_ref::<ChuOp>() {
            code.push_str(&format!("  {} / {};", 
                self.generate_cuda_expr(&div.lhs), 
                self.generate_cuda_expr(&div.rhs)));
        } else if let Some(ret) = op.as_any().downcast_ref::<FanhuiOp>() {
            if let Some(value) = &ret.value {
                code.push_str(&format!("  return {};", self.generate_cuda_expr(value)));
            } else {
                code.push_str("  return;");
            }
        }
        
        code.push_str("\n");
        code
    }
    
    /// 生成CUDA表达式
    fn generate_cuda_expr(&self, op: &Box<dyn mlir::ops::HuanOp>) -> String {
        if let Some(int_lit) = op.as_any().downcast_ref::<IntLitOp>() {
            int_lit.value.to_string()
        } else if let Some(ident) = op.as_any().downcast_ref::<IdentOp>() {
            ident.name.clone()
        } else {
            "0".to_string()
        }
    }
    
    /// 生成HIP代码
    fn generate_hip(&self, module: &mlir::ModuleOp) -> String {
        let mut code = String::new();
        code.push_str("// HIP code generated by HuanLang\n");
        code.push_str("#include <hip/hip_runtime.h>\n\n");
        
        for op in &module.ops {
            if let Some(func) = op.as_any().downcast_ref::<HanshuOp>() {
                code.push_str(&format!("__global__ void {}() {{\n", func.name));
                for body_op in &func.body {
                    code.push_str(&self.generate_hip_body(body_op));
                }
                code.push_str("}\n\n");
            }
        }
        
        code
    }
    
    /// 生成HIP代码体
    fn generate_hip_body(&self, op: &Box<dyn mlir::ops::HuanOp>) -> String {
        let mut code = String::new();
        
        if let Some(add) = op.as_any().downcast_ref::<JiaOp>() {
            code.push_str(&format!("  {} + {};", 
                self.generate_hip_expr(&add.lhs), 
                self.generate_hip_expr(&add.rhs)));
        } else if let Some(sub) = op.as_any().downcast_ref::<JianOp>() {
            code.push_str(&format!("  {} - {};", 
                self.generate_hip_expr(&sub.lhs), 
                self.generate_hip_expr(&sub.rhs)));
        } else if let Some(mul) = op.as_any().downcast_ref::<ChengOp>() {
            code.push_str(&format!("  {} * {};", 
                self.generate_hip_expr(&mul.lhs), 
                self.generate_hip_expr(&mul.rhs)));
        } else if let Some(div) = op.as_any().downcast_ref::<ChuOp>() {
            code.push_str(&format!("  {} / {};", 
                self.generate_hip_expr(&div.lhs), 
                self.generate_hip_expr(&div.rhs)));
        } else if let Some(ret) = op.as_any().downcast_ref::<FanhuiOp>() {
            if let Some(value) = &ret.value {
                code.push_str(&format!("  return {};", self.generate_hip_expr(value)));
            } else {
                code.push_str("  return;");
            }
        }
        
        code.push_str("\n");
        code
    }
    
    /// 生成HIP表达式
    fn generate_hip_expr(&self, op: &Box<dyn mlir::ops::HuanOp>) -> String {
        if let Some(int_lit) = op.as_any().downcast_ref::<IntLitOp>() {
            int_lit.value.to_string()
        } else if let Some(ident) = op.as_any().downcast_ref::<IdentOp>() {
            ident.name.clone()
        } else {
            "0".to_string()
        }
    }
    
    /// 生成OpenCL代码
    fn generate_opencl(&self, module: &mlir::ModuleOp) -> String {
        let mut code = String::new();
        code.push_str("// OpenCL code generated by HuanLang\n");
        code.push_str("__kernel void kernel_main() {\n");
        
        for op in &module.ops {
            if let Some(func) = op.as_any().downcast_ref::<HanshuOp>() {
                code.push_str(&format!("  // Function: {}\n", func.name));
                for body_op in &func.body {
                    code.push_str(&self.generate_opencl_body(body_op));
                }
            }
        }
        
        code.push_str("}\n");
        code
    }
    
    /// 生成OpenCL代码体
    fn generate_opencl_body(&self, op: &Box<dyn mlir::ops::HuanOp>) -> String {
        let mut code = String::new();
        
        if let Some(add) = op.as_any().downcast_ref::<JiaOp>() {
            code.push_str(&format!("    {} + {};", 
                self.generate_opencl_expr(&add.lhs), 
                self.generate_opencl_expr(&add.rhs)));
        } else if let Some(sub) = op.as_any().downcast_ref::<JianOp>() {
            code.push_str(&format!("    {} - {};", 
                self.generate_opencl_expr(&sub.lhs), 
                self.generate_opencl_expr(&sub.rhs)));
        } else if let Some(mul) = op.as_any().downcast_ref::<ChengOp>() {
            code.push_str(&format!("    {} * {};", 
                self.generate_opencl_expr(&mul.lhs), 
                self.generate_opencl_expr(&mul.rhs)));
        } else if let Some(div) = op.as_any().downcast_ref::<ChuOp>() {
            code.push_str(&format!("    {} / {};", 
                self.generate_opencl_expr(&div.lhs), 
                self.generate_opencl_expr(&div.rhs)));
        } else if let Some(_ret) = op.as_any().downcast_ref::<FanhuiOp>() {
            code.push_str("    return;");
        }
        
        code.push_str("\n");
        code
    }
    
    /// 生成OpenCL表达式
    fn generate_opencl_expr(&self, op: &Box<dyn mlir::ops::HuanOp>) -> String {
        if let Some(int_lit) = op.as_any().downcast_ref::<IntLitOp>() {
            int_lit.value.to_string()
        } else if let Some(ident) = op.as_any().downcast_ref::<IdentOp>() {
            ident.name.clone()
        } else {
            "0".to_string()
        }
    }
    
    /// 生成Vulkan SPIR-V代码
    fn generate_vulkan(&self, module: &mlir::ModuleOp) -> String {
        let mut code = String::new();
        code.push_str("// Vulkan SPIR-V code generated by HuanLang\n");
        code.push_str("// This is a placeholder for SPIR-V assembly\n");
        code.push_str("OpCapability Shader\n");
        code.push_str("OpMemoryModel Logical GLSL450\n");
        code.push_str("OpEntryPoint GLCompute %main \"main\"\n");
        code.push_str("%main = OpFunction %void None %funcType\n");
        code.push_str("%entry = OpLabel\n");
        
        // 生成函数体
        for op in &module.ops {
            if let Some(func) = op.as_any().downcast_ref::<HanshuOp>() {
                code.push_str(&format!("// Function: {}\n", func.name));
            }
        }
        
        code.push_str("OpReturn\n");
        code.push_str("OpFunctionEnd\n");
        code
    }
}

impl CodeGenerator for GpuBackend {
    fn new(target_triple: TargetTriple, options: CodeGenOptions) -> Self {
        let target = Self::from_triple(&target_triple);
        Self {
            target,
            options,
        }
    }

    fn generate(&mut self, mlir_module: &mlir::ModuleOp) -> Result<Vec<u8>, CodeGenError> {
        println!("Generating GPU code for target: {:?}", self.target);
        
        let code = match self.target {
            GpuTarget::Cuda => self.generate_cuda(mlir_module),
            GpuTarget::Hip => self.generate_hip(mlir_module),
            GpuTarget::OpenCL => self.generate_opencl(mlir_module),
            GpuTarget::Vulkan => self.generate_vulkan(mlir_module),
        };
        
        Ok(code.into_bytes())
    }

    fn emit_assembly(&mut self, mlir_module: &mlir::ModuleOp) -> Result<String, CodeGenError> {
        let code = match self.target {
            GpuTarget::Cuda => self.generate_cuda(mlir_module),
            GpuTarget::Hip => self.generate_hip(mlir_module),
            GpuTarget::OpenCL => self.generate_opencl(mlir_module),
            GpuTarget::Vulkan => self.generate_vulkan(mlir_module),
        };
        
        Ok(code)
    }

    fn link(&self, _objects: Vec<PathBuf>, _output: PathBuf) -> Result<(), LinkError> {
        // GPU通常不需要链接，返回成功
        Ok(())
    }
}
