[package]
name = "features-example"
version = "0.3.0"

[dependencies]
网络 = { version = "0.3", optional = true }
序列化 = { version = "1.0", optional = true }
数据库 = { version = "2.0", optional = true }

[features]
default = ["std"]
std = []
network = ["网络"]
json = ["序列化"]
db = ["数据库"]
full = ["network", "json", "db"]
